animals/urls.py
# -*- coding: utf-8 -*-
from django.urls import path

from animals.views import animals_list_view, animals_id_view
app_name="animals"
urlpatterns=[
    path("",animals_list_view, name = "a"),
    path("animals/<int:pk>", animals_id_view, name="animals"),
]

custom_auth/urls.py
# -*- coding: utf-8 -*-
import django.views.generic.edit
from django.contrib.auth import views as auth_views
from django.contrib.auth.forms import UserCreationForm
from django.urls import path, reverse_lazy

app_name = 'custom_auth'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('change_password/', auth_views.PasswordChangeView.as_view() ),
    #path('change_password/', django.core ),
    path('gigi/', django.views.generic.edit.CreateView.as_view(form_class=UserCreationForm, template_name='registration/login.html', success_url=reverse_lazy("custom_auth:login"))),



]

siteinfo/urls.py
from django.urls import path

from siteinfo.views import home_view, info_view

app_name = "siteinfo"
urlpatterns = [
    path('home/', home_view, name = "home"),
    path('info/', info_view, name = "info"),
]# -*- coding: utf-8 -*-

zoopark/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("animals/", include("animals.urls", namespace="animals")),
    path('about/', include('siteinfo.urls', namespace='info')),
    path('auth/', include('custom_auth.urls', namespace='custom_auth')),
]
if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

animals/models.py
from django.db import models

from django.contrib.auth.models import User

# Create your models here.
class Animals(models.Model):
    kind=models.CharField(max_length=32, verbose_name="Вид животного")
    name=models.CharField(max_length=128, verbose_name="Имя животного")
    text=models.TextField(blank=False, verbose_name="Описание")
    img=models.ImageField(upload_to="%Y/%m/%d/", verbose_name="Изображение")
    published=models.BooleanField(default=False, verbose_name="Опубликовано")
    publish_date=models.DateTimeField(auto_now_add=True, verbose_name="Дата публикации")
    change_date=models.DateTimeField(auto_now=True, verbose_name="Дата изменения")
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Автор")
    likes = models.ManyToManyField(User, related_name="liked_posts", verbose_name="Лайки")

def __str__(self):
    return self.name 
    class Meta:
        verbose_name = "Животное"
        verbose_name_plural = "Животные"
        ordering = ["-publish_date", "-change_date"]
# Create your models here.

comment/models.py
from django.db import models
from animals.models import Animals


class Comment(models.Model):
    text = models.TextField(blank=False) 
    date_of_create = models.DateTimeField(auto_now_add=True)
    author = models.CharField(max_length=32)
    animals = models.ForeignKey(Animals, on_delete=models.CASCADE)
    published = models.BooleanField(default=False) 

    def __str__(self):
        return self.text [ :32] + '...'    

    class Meta:
        ordering = ('-date_of_create', )

custom_auth/models.py
from django.db import models

# Create your models here.

siteinfo/models.py
from django.db import models

# Create your models here.

comment/forms.py
from django import forms

from comment.models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        exclude = ('date_of_create','published','animals')

animals/views.py
from django.shortcuts import render, get_object_or_404

# Create your views here.
from animals.models import Animals
from comment.models import Comment
from comment.forms import CommentForm


def animals_list_view (request):
    animals=Animals.objects.filter(published=True)
    context={"animals_list": animals,'page':'animals'}
    return render(request, "animals/animals_list.html",context)

def animals_id_view(request, pk):
    pk = get_object_or_404(Animals, pk=pk)
    context = {"pk": pk,'page':'animals'}
    comments = Comment.objects.filter(animals = pk, published=True)
    if request.method=="POST": 
         form = CommentForm(request.POST) 
         if form.is_valid(): 
           comment =  form.save(commit=False) 
           comment.animals = pk 
           comment.save() 
           form = CommentForm() 
    else:
        form = CommentForm()
    context = {"pk": pk,'page':'animals', 'comments_list':comments, 'form':form}
    return render(request, "animals/animals_id.html", context)

comment/views.py
from django.shortcuts import render

# Create your views here.

custom_auth/views.py
from django.shortcuts import render

# Create your views here.

siteinfo/views.py
from django.shortcuts import render

def home_view(request):
    context = {"page": "home"}
    return render(request, 'siteinfo/home.html', context)

def info_view(request):
    context = {"page": "info"}
    return render(request, 'siteinfo/info.html', context)

animals/templates/animals/animals_id.html
{% extends 'root.html' %}
{% block content %}
    <div class="ms-4 me-4">
        <h1>{{ pk.kind }}</h1>
        <p>{{ pk.name }}</p>
        <img src="{{ pk.img.url }}" alt="" width="400px" height="300px">
        <p class="fs-4">{{ pk.text }}</p>
        <p>{{ pk.author.username }}</p>
        <p>Дата: Сохранения-{{ pk.publish_date }}</p>
        <p>Дата: Последного-{{ pk.change_date }}</p>
    </div>
    <div class="mt-3">
        <h1>Комментарии</h1>
        <form action="{% url 'animals:animals' pk.pk %}" method="post">
            {% csrf_token %}
            {{ form.as_p }} 
            <input class="btn btn-success" value="Отправить" type="submit">
        </form>
        {% for comment in comments_list %}
            <div>
                <p>{{ comment.author }}</p>
                <p>{{ comment.text }}</p>
                <p>{{ comment.date_of_create }}</p>
            </div>
            {% empty %}
            <h3>Будь первым</h3>
        {% endfor %}
    </div>
{% endblock %}

animals/templates/animals/animals_list.html
{% extends "root.html" %}
{% load thumbnail %}
{% block content %}
<ul class="ps-3 list-unstyled pe-3">
    {% for animals in animals_list %}
        <li>
       <div class="d-inline-flex border" style="padding: 10px 0px 0px 10px;">
            <img src="{{ animals.img.url }}" width="300px" height="200px" style="object-fit: cover;" class="">
            <div class="ms-3 mt-0">
                <a href="{% url 'animals:animals' animals.pk %}" class="d-block ms-3">
                    <p class="fs-2">{{ animals.kind }}</p>
                    <p class="fs-2">{{ animals.name }}</p>
                </a>
                <p class="ps-3 pt-0 fs-3">{{ animals.text|truncatechars:128 }}</p>
            </div>
        </div>
        </li>
    {% endfor %}
</ul>
{% endblock %}

siteinfo/templates/siteinfo/home.html
{% extends 'root.html' %}
{% block content %}
    <!DOCTYPE html>
    <html lang="ru">
        <head>
            <meta charset="utf-8" />
           
        </head>
        <body>
            <table
            border="1"
            align="center"
            rules="rows"
            style="width:60%;">
            <tr>
            <td>
            <table
            border="1"
            background="images/168.png"
            bgcolor="#7FFFD4"
            cellpadding="10"
            style="width:100%; border-radius:5px;">
            <tr>
            <th>
            <h1>Карточка сайта зоопарка</h1>
            <h3>;) не ставтье пожалуйста 2(((( я просто не знала, что сделать</h3>
            </th>
            </tr>
            </table>
            <table
            border="1"
            bgcolor="#e6e6fa"
            cellpadding="10"
            style="width:100%; border-radius:5px;">
            <tr>
            <td
            rowspan="2"
            style="width:80%">
            <h2>Zoopark</h2>
            <p style="text-indent:20px">
            Что такое - зоопарк? Зоологический парк представляет собой учреждение, в котором содержат животных в неволе для демонстрации, изучения, сохранения и воспроизводства. Зоопарки создаются в научно-просветительских целях. Они помогают распространить знания о многообразии животного мира, пропагандируя охрану и сохранение генофонда редких, исчезающих особей.</p>
            
            <p style="text-indent:20px">
           Ограниченность территории, на которой содержатся животные, - главная отличительная особенность зоопарка (фото зоологических парков и животных есть в статье). Зоопарк имеет сходство с зонами отдыха, ведь у него есть четкие границы. Специально созданные помещения с приближенными природными условиями для жизни становятся местом обитания многих видов животных. Как правило, территория зоопарка огромная, в отличие от зоосада. Многие учреждения были организованы на базе частных коллекций, цирков и выставок. В России к старейшим зоопаркам, основанным в 19 веке, относят Казанский, Пензенский, Санкт-Петербургский и Московский.</p>
            
            </td>
            
           
           
            </tr>
         
            <tr>
           
            <td
            bgcolor="#e6e6fa"
            align="center">
            <h3>Общая информация</h3>
            <p>Текст общей информации или реклама</p>
            
            </td>
            </tr>
            </table>
            
            <table
            border="1"
            bgcolor="#7FFFD4"
            height="100"
            cellpadding="10"
            style="width:100%; border-radius:5px;">
            <tr>
  
            <th>
            <h3>8 000 000 00 00</h3>
            </th>
            </tr>
            </table>
            </td>
            </tr>
            </table>
        </body>
        </html>
{% endblock %}

siteinfo/templates/siteinfo/info.html
{% extends 'root.html' %}
{% block content %}
    <p>Я глупая девочка забыла сдать сайт вовремя и мне грустно. Я уже столько дней пытаюсь сделать и у меня было много ошибок и вчера у меня была депрессия в 0 лет.</p>
{% endblock %}

templates/root.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
    <head>
        <meta charset="UTF-8">
        <title>Zoopark</title>
        <script src = '{% static "js/bootstrap.min.js" %}'></script>
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <style>
            .off-link-decoration {
                text-decoration: none;
                color: red;
                font-size: 25px;
                
            }

            .active .off-link-decoration {
                color: orange;
            }

            .off-link-decoration:hover {
                text-decoration: underline;
            }
        </style>
    </head>
        <body class="mb-0 mt-0 align-content-center justify-content-center d-flex" style="height: 100%; background-color: #EE82EE">
            <div class="w-75" style="height: 100%; background-color: #E6E6FA;">
                <div class="w-100 ps-3 pt-3 pb-3 mb-3 d-inline-flex align-items-center" style="border: 2px solid pink; border-radius: 0 0 4px 4px;">
                    <h1 style="color:#4B0082;">MyZoo</h1>
                    <ul class="fs-5 ms-4 h-25 list-group list-group-horizontal">
                        <li class="list-group-item {% if page == 'home' %} active {% endif  %}"><a href="{% url 'info:home' %}" class="off-link-decoration">Home</a></li>
                        <li class="list-group-item {% if page == 'animals' %} active {% endif  %}"><a href="{% url 'animals:a' %}" class="off-link-decoration">Animals</a></li>
                        <li class="list-group-item {% if page == 'info' %} active {% endif  %}"><a href="{% url 'info:info' %}" class="off-link-decoration">Info</a></li>
                    </ul>
                </div>
                <div class="content">
                    {% block content %}
                    {% endblock %}
                </div>
            </div>
            
        </body>
    </html>